@startuml

node "Cage 0" {
        node "Tunnel 0" as tunnel_0_0 {
                [Motor 0] as motor_0_0_0
                [Motor 1] as motor_0_0_1
                [Motor 2] as motor_0_0_2
        }
        node "Tunnel 1" as tunnel_0_1 {
                [Motor 0] as motor_0_1_0
                [Motor 1] as motor_0_1_1
                [Motor 2] as motor_0_1_2
        }
}

node "Cage 1" {
        node "Tunnel 0" as tunnel_1_0 {
                [Motor 0] as motor_1_0_0
                [Motor 1] as motor_1_0_1
                [Motor 2] as motor_1_0_2
                [Motor 3] as motor_1_0_3
                [Motor 4] as motor_1_0_4
        }
}

@enduml
